image: atlassian/default-image:2

pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - pipe: atlassian/ssh-run:0.2.6
            variables:
              SSH_USER: $SSH_USER
              SERVER: $SSH_SERVER
              COMMAND: '~/torunar.sh'
              PORT: $SSH_PORT