CIDER_mainTitle="# /usr/bin/torunar"
CIDER_mainTitlePaged="${CIDER_mainTitle} :: Страница <!--{var:pageNumber}-->"
CIDER_pageLinkPrevText="&larr;"
CIDER_pageLinkNextText="&rarr;"
CIDER_pageLinkCurrText="<!--{var:pageNumber}-->"
CIDER_blogName="# /usr/bin/torunar"
CIDER_blogDescription=""
CIDER_footerLinks="<a class=\"rss\" href=\"/rss.xml\">RSS</a> <a class=\"github\" href=\"https://github.com/torunar/\">GitHub</a>"
CIDER_commentsTitle="Комментарии"
