CIDER_mainTitle="Блог"
CIDER_mainTitlePaged="${CIDER_mainTitle} :: Страница <!--{var:pageNumber}-->"
CIDER_pageLinkPrevText="&larr;"
CIDER_pageLinkNextText="&rarr;"
CIDER_pageLinkCurrText="<!--{var:pageNumber}-->"
CIDER_blogName="Михаил Щекотов"
CIDER_blogDescription="Веб-разработка и пепяки"
