name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare Cider
      run: chmod +x "${GITHUB_WORKSPACE}/cider/cider.sh"

    - name: Install dependencies
      run: sudo apt install -y markdown webp

    - name: Build
      run: ${GITHUB_WORKSPACE}/cider/cider.sh -i="${GITHUB_WORKSPACE}/posts" -o="${GITHUB_WORKSPACE}/www" -l="${GITHUB_WORKSPACE}/cider_localization.sh" -c="${GITHUB_WORKSPACE}/cider_config.sh"

    - name: Convert images
      run: for i in $(find "${GITHUB_WORKSPACE}/www" -name '*.jpg' -o -name '*.png'); do cwebp -quiet -q 95 $i -o $i.webp; done

    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: www
        path: www
        retention-days: 1
