name: Deploy

on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Prepare Cider
      run: chmod +x "${GITHUB_WORKSPACE}/cider/cider.sh"

    - name: Install dependencies
      run: sudo apt install -y markdown

    - name: Build
      run: ${GITHUB_WORKSPACE}/cider/cider.sh -i="${GITHUB_WORKSPACE}/posts" -o="${GITHUB_WORKSPACE}/www" -l="${GITHUB_WORKSPACE}/cider_localization.sh" -c="${GITHUB_WORKSPACE}/cider_config.sh"

    - name: Upload to GitHub Pages
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: 'www'
        destination-github-username: 'torunar'
        destination-repository-name: 'torunar.github.io'
        user-email: deployer@localhost
        target-branch: master
